### ISSUE TITLE
Leaving vent's management console open causes crash

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/vent#437]
Haven't been able to determine cause, but error states something to the effect of "too many files open," which may be the result of automated refreshing.

Edit: actual error below.

```(dev) alice@ubuntu:~/dev/vent$ vent
Traceback (most recent call last):
  File "/home/alice/dev/bin/vent", line 4, in <module>
    __import__('pkg_resources').run_script('vent==0.3.2.dev0', 'vent')
  File "/home/alice/dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/alice/dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/alice/dev/local/lib/python2.7/site-packages/vent-0.3.2.dev0-py2.7.egg/EGG-INFO/scripts/vent", line 11, in <module>
    
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/wgtitlefield.py", line 119, in edit
    self.entry_widget.edit()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/wgtextbox.py", line 524, in edit
    self.get_and_use_key_press()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/wgwidget.py", line 575, in get_and_use_key_press
    return self.try_while_waiting()
  File "/home/alice/dev/local/lib/python2.7/site-packages/npyscreen/wgwidget.py", line 557, in try_while_waiting
    self.parent.while_waiting()
  File "build/bdist.linux-x86_64/egg/vent/menus/main.py", line 45, in while_waiting
  File "build/bdist.linux-x86_64/egg/vent/helpers/meta.py", line 189, in Uptime
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1227, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/lib/python2.7/subprocess.py", line 1179, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by cglewis** [comment]
i had an issue with this before, i thought i had fixed it with `close_fds` for subprocesses and an additional `time.sleep` to give time for the processes to close, but maybe i missed one.  is your fork synced up?

**Comment by lilchurro** [comment]
So far as I can tell, it's in sync with its upstream version of experimental.

**Comment by cglewis** [comment]
was able to reproduce, working on a fix.

**Comment by cglewis** [comment]
this should be fixed now, but feel free to reopen if you experience this issue again.
