### ISSUE TITLE
The build() in vent.api.actions fails when building tools

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/vent#792]
This can be reproduced by running test_build() in test_api_actions.py

**Comment by lilchurro** [comment]
In stepping through the builder function, it's clear that the function doesn't run to completion, and that errors tend to happen silently, so it's not immediately clear (aside from the printed logs trailing off) that the function isn't complete.

I've narrowed the problem down to the following section:
```# remove untagged images
        untagged = self.d_client.images.list(filters={"label": "vent",
                                                      "dangling": "true"})
        if untagged:
            deleted_images = ""
            for image in untagged:
                deleted_images = '\n'.join([deleted_images, image.id])
                self.d_client.images.remove(image.id, force=True)
            self.logger.info("removed dangling images:" + deleted_images)
        else: # DEBUG
            self.logger.info("DEBUG: Nothing was untagged/dangling.")
```
When manually running this, there is the potential for a conflict with Docker, which will have to be caught:
```>>> for image in untagged:
...     d_client.images.remove(image.id, force=True)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/alice/.local/lib/python2.7/site-packages/docker/models/images.py", line 281, in remove
    self.client.api.remove_image(*args, **kwargs)
  File "/home/alice/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/alice/.local/lib/python2.7/site-packages/docker/api/image.py", line 458, in remove_image
    self._raise_for_status(res)
  File "/home/alice/.local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/alice/.local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("conflict: unable to delete 6eecee5a2193 (cannot be forced) - image is being used by running container f547ea663e3e")```

But, I am not entirely sure what is the most desireable way to handle this... probably because of my limited knowledge of Docker. Will probably need the @CyberReboot/team 's input on this.

**Comment by cglewis** [comment]
looks like in this case, there are containers that exist that are using the old images, so when it builds new ones and tries to delete the old ones that still have containers, it can't.  i'll assign this issue to me.
